import { Box, Grid, Typography, Paper, Container } from '@mui/material';
import { useTheme } from '@mui/material/styles';

export default function MidoriEarthNKP() {
  const theme = useTheme();

  return (
    <Box id="midori-earth-nkp" py={12} sx={{
      background: 'linear-gradient(to bottom right, #ffffff, rgba(241,245,249,0.4), #ffffff)',
      position: 'relative',
      mt: 1
    }}>
      <Typography
          variant="h2"
          textAlign="center"
          sx={{
            fontWeight: 'bold',
            fontFamily: 'Montserrat, sans-serif',
            background: 'linear-gradient(90deg, #0d8548, #9fc45b)',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            lineHeight: 1.2,
            mb: 4
          }}
        >
          Bridging Earth and Blockchain
        </Typography>
        <Typography
          variant="h5"
          textAlign="center"
          sx={{
            fontWeight: 'bold',
            fontFamily: 'Montserrat, sans-serif',
            background: '#000',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            lineHeight: 1.2,
            mb: 4
          }}
        >
          How Midori Earth Powers NKP’s Value Engine
        </Typography>
      <Box sx={{ position: 'absolute', inset: 0, overflow: 'hidden', pointerEvents: 'none' }}>
        <Box sx={{ position: 'absolute', top: 80, left: 40, width: 128, height: 128, bgcolor: 'rgba(13,133,72,0.05)', borderRadius: '50%', filter: 'blur(40px)' }} />
        <Box sx={{ position: 'absolute', bottom: 80, right: 40, width: 160, height: 160, bgcolor: 'rgba(159,196,91,0.05)', borderRadius: '50%', filter: 'blur(40px)' }} />
      </Box>

      <Container sx={{ position: 'relative', zIndex: 10 }}>
        <Box maxWidth="xl" mx="auto">
          <Paper elevation={6} sx={{ backgroundColor: 'rgba(255,255,255,0.8)', backdropFilter: 'blur(10px)', border: '1px solid #e5e7eb', borderRadius: 4, overflow: 'hidden' }}>
            <Grid container>
              <Grid item xs={12} lg={6} sx={{ borderRight: { lg: '1px solid #e5e7eb' }, p: { xs: 4, lg: 6 }, bgcolor: 'linear-gradient(to bottom right, #ffffff, rgba(249,250,251,0.5))', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
                <Box>
                  <Typography
                    variant="h4"
                    fontWeight="bold"
                    gutterBottom
                    sx={{ background: 'linear-gradient(to right, #0d8548, #9fc45b)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', fontFamily: 'Montserrat, sans-serif', textTransform: 'uppercase' }}
                  >
                    Midori Earth and NKP
                  </Typography>

                  <Box sx={{ color: '#374151', mt: 4, textAlign: "justify", fontWeight: "normal" }}>
                    <Typography paragraph fontWeight="normal">
                      <strong>Midori Earth</strong> is the operational parent company that owns and manages the productive assets and initiatives. As a global developer of high-integrity real-world asset projects and technology solutions, Midori Earth supplies the access to projects that profits split between reinvestment in future real-world initiatives and token buybacks.
                    </Typography>
                    <Typography paragraph>
                      <strong>Non Kyoto Protocol</strong> is a 50% stakeholder in the Midori Earth company. The NKP token grants effective control over the Non Kyoto Protocol, giving token holders a tangible seat at the table to capture value from all the assets and revenue of Midori Earth. This is a stark contrast to what many are used to in the cryptocurrency space, where the benefit of the company and the benefit of the token holders may be at odds. Midori Earth and NKP stand for integrity, transparency, and appropriately sharing all the value generated by our earth-restoring initiatives.
                    </Typography>
                    <Typography paragraph>
                      In addition to being a 50% ownership partner with Non Kyoto Protocol, Midori Earth has committed 30% of its net profits to buying back the NKP token.
                    </Typography>
                    <Typography paragraph>
                      This direct pipeline to established projects, real-world assets, global partners, and technology developments, ensures a steady flow of tangible value into NKP. This unlocks access to NKP holders to high-value projects only available to institutional investors.
                    </Typography>
                    <Typography paragraph>
                      <strong>NKP</strong> creates a real and verifiable financial system where off-chain assets generate yield, this yield funds additional investments and revenue, which creates sustainable returns.
                    </Typography>
                  </Box>
                </Box>
              </Grid>

              <Grid item xs={12} lg={6} sx={{ p: { xs: 4, lg: 6 }, background: 'linear-gradient(to bottom right, #f9fafb, #ffffff)' }}>
                <Typography
                  variant="h5"
                  fontWeight="bold"
                  textAlign="center"
                  gutterBottom
                  sx={{ textTransform: 'uppercase', fontFamily: 'Montserrat, sans-serif', color: '#1f2937' }}
                >
                  NKP Value Generation
                </Typography>

                <Box mt={4} display="flex" flexDirection="column" gap={3}>
                  {[
                    {
                      title: '100,000+ Carbon Credits Committed',
                      text: 'Backed by real-world impact, NKP has secured over 100,000 high-integrity carbon credits across verified projects. These credits anchor the protocol in tangible off-chain diversified revenues.'
                    },
                    {
                      title: '3-Phase Reinvestment Model',
                      text: 'Revenue flows through a closed-loop reinvestment engine. First, profits fund NKP token buybacks. Second, supply is reduced through burning or long-term locking. Third, capital is reinvested into new credit-generating assets.'
                    },
                    {
                      title: 'Institutional-Grade Access for All',
                      text: 'NKP gives everyday holders the chance to access exclusive environmental assets typically reserved for large funds and institutional players. No accreditation required.'
                    },
                    {
                      title: 'Transparent On-Chain Accounting',
                      text: 'Every credit, buyback, and reinvestment is publicly visible on-chain. Nothing is hidden. Token holders can trace how value moves from real-world assets into the ecosystem.'
                    }
                  ].map(({ title, text }) => (
                    <Paper
                      key={title}
                      elevation={3}
                      sx={{ p: 3, borderLeft: '4px solid #0d8548', transition: 'box-shadow 0.3s', '&:hover': { boxShadow: 6 } }}
                    >
                      <Typography variant="h6" fontWeight="bold" gutterBottom sx={{ color: '#111827' }}>{title}</Typography>
                      <Typography variant="body2" sx={{ color: '#374151' }}>{text}</Typography>
                    </Paper>
                  ))}
                </Box>
              </Grid>
            </Grid>
          </Paper>
        </Box>
      </Container>
    </Box>
  );
}
